import React, { useState, useEffect } from 'react';
import { invoke } from '@tauri-apps/api/core';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from '../ui/dialog';
import { Button } from '../ui/button';
import {
  FileText,
  DollarSign,
  Scale,
  Calendar,
  User,
  Download,
  Printer,
  Receipt
} from 'lucide-react';

const ShiftReports = ({ open, onClose }) => {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(false);
  const [selectedReport, setSelectedReport] = useState(null);

  useEffect(() => {
    if (open) {
      loadReports();
    }
  }, [open]);

  const loadReports = async () => {
    setLoading(true);
    try {
      const data = await invoke('get_shift_reports');
      setReports(data);
    } catch (error) {
      console.error('Failed to load shift reports:', error);
    } finally {
      setLoading(false);
    }
  };

  const formatCurrency = (amount) => {
    return new Intl.NumberFormat('id-ID', {
      style: 'currency',
      currency: 'IDR',
      minimumFractionDigits: 0
    }).format(amount);
  };

  const formatDateTime = (dateString) => {
    return new Date(dateString).toLocaleString('id-ID', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  };

  const getReportSummary = (report) => {
    const data = report.data;
    const cashSummary = data.cash_summary || {};
    return {
      totalCashIn: cashSummary.total_cash_in || 0,
      totalCashOut: cashSummary.total_cash_out || 0,
      netMovement: cashSummary.net_movement || 0,
      initialCash: cashSummary.initial_cash || 0,
      expectedCash: cashSummary.expected_cash || 0,
      actualCash: cashSummary.actual_cash || 0,
      difference: cashSummary.difference || 0,
    };
  };

  const exportToCSV = (report) => {
    const summary = getReportSummary(report);
    const shiftInfo = report.data.shift_info || {};
    
    const csvData = [
      ['SHIFT REPORT'],
      [''],
      ['Report Information'],
      ['Report ID', report.id],
      ['Generated At', formatDateTime(report.generated_at)],
      ['Generated By', report.generated_by],
      ['Report Type', report.report_type],
      [''],
      ['Shift Information'],
      ['Shift ID', report.shift_id],
      ['Started', formatDateTime(shiftInfo.start_time)],
      ['Ended', formatDateTime(shiftInfo.end_time)],
      ['Cashier', shiftInfo.user_name || 'N/A'],
      ['Register', shiftInfo.register_name || 'N/A'],
      [''],
      ['Cash Summary'],
      ['Initial Cash', summary.initialCash],
      ['Cash In', summary.totalCashIn],
      ['Cash Out', summary.totalCashOut],
      ['Expected Cash', summary.expectedCash],
      ['Actual Cash', summary.actualCash],
      ['Difference', summary.difference],
      ['Net Movement', summary.netMovement],
      [''],
      ['Statistics'],
      ['Total Movements', report.data.movements?.length || 0],
      ['Total Transactions', report.data.transactions?.length || 0],
    ];
    
    const csvContent = csvData
      .map(row => row.map(cell => `"${cell}"`).join(','))
      .join('\n');
    
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `shift_report_${report.shift_id.slice(0, 8)}.csv`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const exportToPDF = (report) => {
    // ... existing A4 PDF format ...
  };

  const printToPOS58 = (report) => {
    const summary = getReportSummary(report);
    const shiftInfo = report.data.shift_info || {};
    
    // POS58 thermal printer format (54mm width)
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      const formatNum = (n) => new Intl.NumberFormat('id-ID').format(n);
      
      printWindow.document.write(`
        <!DOCTYPE html>
        <html>
        <head>
          <title>Shift Report - ${report.shift_id.slice(0, 8)}</title>
          <style>
            @page { margin: 0; size: 58mm auto; }
            body { 
              font-family: 'Courier New', monospace; 
              width: 58mm; 
              padding: 2mm; 
              font-size: 10px;
              line-height: 1.2;
            }
            .center { text-align: center; }
            .bold { font-weight: bold; }
            .right { text-align: right; }
            .dashed { border-bottom: 1px dashed #000; margin: 5px 0; }
            .title { font-size: 12px; font-weight: bold; margin-bottom: 5px; }
            .section { margin: 8px 0; }
          </style>
        </head>
        <body>
          <div class="center title">SHIFT REPORT</div>
          <div class="center">${shiftInfo.register_name || 'Cash Register'}</div>
          <div class="dashed"></div>
          
          <div class="section">
            <div>Kasir: ${shiftInfo.user_name || 'N/A'}</div>
            <div>Mulai: ${formatDateTime(shiftInfo.start_time)}</div>
            <div>Selesai: ${formatDateTime(shiftInfo.end_time)}</div>
          </div>
          
          <div class="dashed"></div>
          
          <div class="section">
            <div class="bold">RINGKASAN KAS</div>
            <div>Kas Awal: Rp ${formatNum(summary.initialCash)}</div>
            <div>Kas Masuk: Rp ${formatNum(summary.totalCashIn)}</div>
            <div>Kas Keluar: Rp ${formatNum(summary.totalCashOut)}</div>
          </div>
          
          <div class="dashed"></div>
          
          <div class="section">
            <div>Kas Esperasi: Rp ${formatNum(summary.expectedCash)}</div>
            <div>Kas Aktual: Rp ${formatNum(summary.actualCash)}</div>
            <div class="bold ${summary.difference >= 0 ? '' : 'negative'}">
              Selisih: ${summary.difference >= 0 ? '+' : ''}Rp ${formatNum(summary.difference)}
            </div>
          </div>
          
          <div class="dashed"></div>
          
          <div class="section">
            <div>Transaksi: ${report.data.transactions?.length || 0}</div>
            <div>Movement: ${report.data.movements?.length || 0}</div>
          </div>
          
          <div class="dashed"></div>
          
          <div class="center section">
            <div>Generated: ${formatDateTime(report.generated_at)}</div>
            <div>*** END OF REPORT ***</div>
          </div>
          
          <script>
            window.onload = function() {
              setTimeout(function() {
                window.print();
                window.onafterprint = function() {
                  window.close();
                };
              }, 300);
            };
          </script>
        </body>
        </html>
      `);
      printWindow.document.close();
    }
  };

  return (
    <Dialog open={open} onOpenChange={onClose}>
      <DialogContent className="max-w-4xl max-h-[80vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <FileText className="w-5 h-5" />
            Shift Reports
          </DialogTitle>
        </DialogHeader>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="space-y-4">
            <h3 className="font-semibold text-foreground">Report History</h3>
            {loading ? (
              <div className="text-center py-8 text-muted-foreground">
                Loading reports...
              </div>
            ) : reports.length === 0 ? (
              <div className="text-center py-8 text-muted-foreground">
                No shift reports available.
              </div>
            ) : (
              <div className="space-y-3">
                {reports.map((report) => {
                  const summary = getReportSummary(report);
                  return (
                    <div
                      key={report.id}
                      onClick={() => setSelectedReport(report)}
                      className={`p-4 rounded-xl border-2 cursor-pointer transition-all duration-200 ${
                        selectedReport?.id === report.id
                          ? 'border-primary bg-primary/5'
                          : 'border-border/50 hover:border-primary/50 hover:bg-accent'
                      }`}
                    >
                      <div className="flex items-center justify-between mb-2">
                        <span className="text-sm font-medium text-muted-foreground">
                          {formatDateTime(report.generated_at)}
                        </span>
                        <span className="text-xs px-2 py-1 rounded-full bg-muted">
                          {report.report_type}
                        </span>
                      </div>
                      <div className="flex items-center gap-2 text-sm mb-2">
                        <User className="w-4 h-4 text-muted-foreground" />
                        <span className="text-muted-foreground">Generated by: {report.generated_by}</span>
                      </div>
                      <div className="flex justify-between text-sm">
                        <span className="text-muted-foreground">Net:</span>
                        <span className={`font-semibold ${
                          summary.netMovement >= 0 ? 'text-green-600' : 'text-red-600'
                        }`}>
                          {formatCurrency(summary.netMovement)}
                        </span>
                      </div>
                    </div>
                  );
                })}
              </div>
            )}
          </div>

          <div className="space-y-4">
            <h3 className="font-semibold text-foreground">Report Details</h3>
            {selectedReport ? (
              <div className="space-y-6">
                <div className="bg-card/50 rounded-xl p-4 space-y-3">
                  <h4 className="font-semibold flex items-center gap-2">
                    <Calendar className="w-4 h-4" />
                    Shift Information
                  </h4>
                  <div className="grid grid-cols-2 gap-3 text-sm">
                    <div className="text-muted-foreground">Shift ID:</div>
                    <div className="font-mono text-xs">{selectedReport.shift_id.slice(0, 8)}...</div>
                    <div className="text-muted-foreground">Started:</div>
                    <div>{formatDateTime(selectedReport.data.shift_info?.start_time)}</div>
                    <div className="text-muted-foreground">Ended:</div>
                    <div>{formatDateTime(selectedReport.data.shift_info?.end_time)}</div>
                  </div>
                </div>

                <div className="bg-card/50 rounded-xl p-4 space-y-3">
                  <h4 className="font-semibold flex items-center gap-2">
                    <DollarSign className="w-4 h-4" />
                    Cash Summary
                  </h4>
                  <div className="space-y-2">
                    <div className="flex justify-between items-center p-2 bg-green-50 dark:bg-green-950/50 rounded-lg">
                      <span className="text-sm text-green-700 dark:text-green-300">Cash In</span>
                      <span className="font-semibold text-green-700 dark:text-green-300">
                        {formatCurrency(summary.totalCashIn)}
                      </span>
                    </div>
                    <div className="flex justify-between items-center p-2 bg-red-50 dark:bg-red-950/50 rounded-lg">
                      <span className="text-sm text-red-700 dark:text-red-300">Cash Out</span>
                      <span className="font-semibold text-red-700 dark:text-red-300">
                        {formatCurrency(summary.totalCashOut)}
                      </span>
                    </div>
                    <div className="flex justify-between items-center p-2 bg-blue-50 dark:bg-blue-950/50 rounded-lg">
                      <span className="text-sm text-blue-700 dark:text-blue-300">Initial Cash</span>
                      <span className="font-semibold text-blue-700 dark:text-blue-300">
                        {formatCurrency(summary.initialCash)}
                      </span>
                    </div>
                    <div className="flex justify-between items-center p-2 bg-blue-50 dark:bg-blue-950/50 rounded-lg">
                      <span className="text-sm text-blue-700 dark:text-blue-300">Expected Cash</span>
                      <span className="font-semibold text-blue-700 dark:text-blue-300">
                        {formatCurrency(summary.expectedCash)}
                      </span>
                    </div>
                    <div className="flex justify-between items-center p-2 bg-blue-50 dark:bg-blue-950/50 rounded-lg">
                      <span className="text-sm text-blue-700 dark:text-blue-300">Actual Cash</span>
                      <span className="font-semibold text-blue-700 dark:text-blue-300">
                        {formatCurrency(summary.actualCash)}
                      </span>
                    </div>
                    <div className={`flex justify-between items-center p-2 rounded-lg ${
                      summary.difference >= 0 ? 'bg-green-50 dark:bg-green-950/50' : 'bg-red-50 dark:bg-red-950/50'
                    }`}>
                      <span className={`text-sm font-medium ${
                        summary.difference >= 0 ? 'text-green-700 dark:text-green-300' : 'text-red-700 dark:text-red-300'
                      }`}>Difference</span>
                      <span className={`font-bold ${
                        summary.difference >= 0 ? 'text-green-700 dark:text-green-300' : 'text-red-700 dark:text-red-300'
                      }`}>
                        {summary.difference >= 0 ? '+' : ''}{formatCurrency(summary.difference)}
                      </span>
                    </div>
                  </div>
                </div>

                <div className="bg-card/50 rounded-xl p-4 space-y-3">
                  <h4 className="font-semibold flex items-center gap-2">
                    <Scale className="w-4 h-4" />
                    Statistics
                  </h4>
                  <div className="grid grid-cols-2 gap-4 text-sm">
                    <div className="text-center p-3 bg-muted/50 rounded-lg">
                      <div className="text-2xl font-bold text-foreground">
                        {selectedReport.data.movements?.length || 0}
                      </div>
                      <div className="text-muted-foreground">Total Movements</div>
                    </div>
                    <div className="text-center p-3 bg-muted/50 rounded-lg">
                      <div className="text-2xl font-bold text-foreground">
                        {selectedReport.data.transactions?.length || 0}
                      </div>
                      <div className="text-muted-foreground">Transactions</div>
                    </div>
                  </div>
                </div>

                <div className="flex gap-3">
                  <Button
                    onClick={() => exportToCSV(selectedReport)}
                    className="flex-1"
                    variant="outline"
                  >
                    <Download className="w-4 h-4 mr-2" />
                    Export CSV
                  </Button>
                  <Button
                    onClick={() => exportToPDF(selectedReport)}
                    className="flex-1"
                  >
                    <Printer className="w-4 h-4 mr-2" />
                    Export PDF
                  </Button>
                  <Button
                    onClick={() => printToPOS58(selectedReport)}
                    className="flex-1"
                    variant="secondary"
                  >
                    <Receipt className="w-4 h-4 mr-2" />
                    Print POS58
                  </Button>
                </div>
              </div>
            ) : (
              <div className="text-center py-16 text-muted-foreground">
                <FileText className="w-12 h-12 mx-auto mb-4 opacity-50" />
                <p>Select a report to view details</p>
              </div>
            )}
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
};

export default ShiftReports;
